# Netlify Configuration for KIXIKILA Frontend

[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish
  publish = "dist"
  
  # Environment variables for build
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Production environment variables
  VITE_API_URL = "https://kixikila-backend.railway.app/api/v1"
  VITE_APP_NAME = "KIXIKILA"
  VITE_APP_VERSION = "1.0.0"
  VITE_ENABLE_VIP_FEATURES = "true"
  VITE_ENABLE_SMS_NOTIFICATIONS = "true"
  VITE_ENABLE_EMAIL_NOTIFICATIONS = "true"
  VITE_ENABLE_ANALYTICS = "true"
  VITE_ENABLE_DEBUG_MODE = "false"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy for development (optional)
[[redirects]]
  from = "/api/*"
  to = "https://kixikila-backend.railway.app/api/:splat"
  status = 200
  force = false
  condition = "Country=ao,pt,br" # Only for specific countries if needed

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.stripe.com https://*.supabase.co wss://*.supabase.co https://kixikila-backend.railway.app; frame-src https://js.stripe.com;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Functions (if using Netlify Functions)
[functions]
  directory = "netlify/functions"

# Form handling (if using Netlify Forms)
[forms]
  spam_protection = true

# Branch deploys
[context.branch-deploy]
  command = "npm run build"
  
[context.branch-deploy.environment]
  VITE_API_URL = "https://kixikila-backend-staging.railway.app/api/v1"
  VITE_ENABLE_DEBUG_MODE = "true"

# Deploy previews
[context.deploy-preview]
  command = "npm run build"
  
[context.deploy-preview.environment]
  VITE_API_URL = "https://kixikila-backend-staging.railway.app/api/v1"
  VITE_ENABLE_DEBUG_MODE = "true"

# Development context
[context.dev]
  command = "npm run dev"
  
[context.dev.environment]
  VITE_API_URL = "http://localhost:3001/api/v1"
  VITE_ENABLE_DEBUG_MODE = "true"